name: GCC i686  Linux GNU

on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: fedora:latest

    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          chmod +x scripts/install-fedora.sh
          ./scripts/install-fedora.sh

      - name: Build cross compiler
        run: |
          chmod +x scripts/build-gcc-i686-linux-gnu.sh
          ./scripts/build-gcc-i686-linux-gnu.sh
